# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
builds:
  -
    builder: rust
    binary: commitr
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
changelog:
  use: github
  groups:
  - title: Features
    regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    order: 0
  - title: "Bug fixes"
    regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: Others
    order: 999
signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
checksum: 
  name_template: "checksums.txt"

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source
